robots:
  crazyflies:
    - name: cf1
      uri: ""
      translation: [-0.5, -0, 0.015]
      orientation: [0, 0, 0, 1]
  turtlebots: 
    - name: tb1
      uri: ""
      translation: [0.859, -0.4427, 0.177]
      orientation: [0, 0, 0, 1]
    - name: tb2
      uri: ""
      translation: [0.858, 0.63, 0.1860]
      orientation: [0, 0, 0, 1]
